import { appSchema, tableSchema } from "@nozbe/watermelondb";
import { SCHEMA_KEYS } from "../shema.keys";

export default appSchema({
  version: 5,
  tables: [
    tableSchema({
      name: SCHEMA_KEYS.CUSTOMER,
      columns: [
        { name: "name", type: "string" },
        { name: "email", type: "string" },
        { name: "phone", type: "string" },
        { name: "address", type: "string" },
        { name: "outstanding", type: "number" },
        { name: "available_credit", type: "number" },
        { name: "status", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "shopId", type: "string" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.SHOP,
      columns: [
        { name: "shopName", type: "string" },
        { name: "shopEmail", type: "string" },
        { name: "shopPhoneNumber", type: "string" },
        { name: "address", type: "string" },
        { name: "panNumber", type: "string" },
        { name: "registrationNumber", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "shopType", type: "string" },
        { name: "shopPanNumber", type: "string" },
        { name: "measuringUnits", type: "string" },
        { name: "userId", type: "string" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.ITEM,
      columns: [
        { name: "item_name", type: "string" },
        { name: "cost_price", type: "number" },
        { name: "selling_price", type: "number" },
        { name: "measurement_unit", type: "string", isOptional: true },
        { name: "shopId", type: "string" },
        { name: "opening_stock", type: "number" },
        { name: "current_stock", type: "number" },
        { name: "low_stock_alert", type: "number" },
        { name: "is_stock_enabled", type: "boolean" },
        { name: "is_active", type: "boolean" },
        { name: "image_url", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.SALES_ITEM,
      columns: [
        { name: "salesId", type: "string", isIndexed: true },
        { name: "itemId", type: "string" },
        { name: "quantity", type: "number" },
        { name: "price", type: "number" },
        { name: "discountAmount", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "itemName", type: "string" },
        { name: "measurementUnit", type: "string" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.SALES,
      columns: [
        { name: "invoiceNumber", type: "string" },
        { name: "shopId", type: "string" },
        { name: "grandTotalAmount", type: "number" },
        { name: "paymentType", type: "string" },
        { name: "status", type: "string" },
        { name: "discountAmount", type: "number" },
        { name: "taxAmount", type: "number" },
        { name: "subTotalAmount", type: "number" },
        { name: "additionalAmount", type: "number" },
        { name: "oldDueAmount", type: "number" },
        { name: "dueAmount", type: "number" },
        { name: "paidAmount", type: "number" },
        { name: "remarks", type: "string" },
        { name: "invoiceDate", type: "number" },
        { name: "customerId", type: "string" },
        { name: "customerName", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.PAYMENT_ACCOUNT,
      columns: [
        { name: "balance", type: "number" },
        { name: "isActive", type: "boolean" },
        { name: "shopId", type: "string" },
        { name: "name", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.EXPENSES,
      columns: [
        { name: "amount", type: "number" },
        { name: "title", type: "string" },
        { name: "remarks", type: "string" },
        { name: "shopId", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: SCHEMA_KEYS.SAVING,
      columns: [
        { name: "amount", type: "number" },
        { name: "title", type: "string" },
        { name: "remarks", type: "string" },
        { name: "shopId", type: "string" },
        { name: "createdAt", type: "number" },
        { name: "updatedAt", type: "number" },
      ],
    }),
  ],
});
